/** [English, Arabic] */
export const dict: Record<string, [string, string]> = {
  brand: ["DentaCare", "دينتاكير"],

  // navigation / shell
  "nav.dashboard": ["Dashboard", "الرئيسية"],
  "nav.queue": ["Live queue", "الدور المباشر"],
  "nav.appointments": ["Appointments", "المواعيد"],
  "nav.patients": ["Patients", "المرضى"],
  "nav.billing": ["Billing", "الفواتير"],
  "nav.reports": ["Reports", "التقارير"],
  "nav.settings": ["Settings", "الإعدادات"],
  "nav.home": ["Home", "الرئيسية"],
  "nav.book": ["Book", "احجز"],
  "nav.live": ["Is it busy?", "هل العيادة مزدحمة؟"],
  "nav.records": ["My records", "سجلّي"],
  "nav.inbox": ["Messages", "الرسائل"],
  "nav.more": ["More", "المزيد"],
  "nav.menu": ["Menu", "القائمة"],
  "nav.tv": ["Waiting-room TV", "شاشة الانتظار"],
  "role.staff": ["Clinic", "العيادة"],
  "role.patient": ["Patient", "مريض"],
  "shell.reset": ["Reset demo data", "إعادة ضبط البيانات التجريبية"],
  "shell.signedInAs": ["Signed in as", "المستخدم"],

  // units / common
  "unit.min": ["min", "د"],
  "unit.days": ["days", "أيام"],
  "unit.months": ["months", "أشهر"],
  "empty.none": ["Nothing here yet.", "لا يوجد شيء بعد."],
  "f.name": ["Full name", "الاسم الكامل"],
  "f.phone": ["Phone", "الهاتف"],
  "f.age": ["Age", "العمر"],
  "f.doctor": ["Doctor", "الطبيب"],
  "f.service": ["Service", "الخدمة"],
  "f.tooth": ["Tooth #", "رقم السن"],

  "status.booked": ["Booked", "محجوز"],
  "status.arrived": ["Arrived", "وصل"],
  "status.done": ["Done", "مكتمل"],
  "status.cancelled": ["Cancelled", "ملغي"],
  "status.no_show": ["No-show", "لم يحضر"],

  "cond.healthy": ["Healthy", "سليم"],
  "cond.cavity": ["Cavity", "تسوّس"],
  "cond.filled": ["Filled", "محشو"],
  "cond.crown": ["Crown", "تاج"],
  "cond.rootcanal": ["Root canal", "علاج عصب"],
  "cond.missing": ["Missing", "مفقود"],

  // dashboard
  "dash.title": ["Today at the clinic", "اليوم في العيادة"],
  "dash.sub": ["Everything happening right now, in one place.", "كل ما يحدث الآن في مكان واحد."],
  "dash.walkin": ["Patient without appointment", "مريض بدون موعد"],
  "dash.book": ["Book appointment", "حجز موعد"],
  "dash.todayAppts": ["Today's appointments", "مواعيد اليوم"],
  "dash.waitingNow": ["Waiting now", "ينتظرون الآن"],
  "dash.inChair": ["in the chair", "على الكرسي"],
  "dash.avgWait": ["Waiting time now", "وقت الانتظار الآن"],
  "dash.forNew": ["if someone walks in now", "لو وصل شخص الآن"],
  "dash.outstanding": ["Outstanding", "مستحقات"],
  "dash.collected": ["Collected", "المحصّل"],
  "dash.liveQueue": ["Live queue", "الدور المباشر"],
  "dash.manage": ["Manage queue", "إدارة الدور"],
  "dash.weekRevenue": ["Revenue, last 7 days", "الإيراد، آخر 7 أيام"],
  "dash.allReports": ["All reports", "كل التقارير"],
  "dash.schedule": ["Today's schedule", "جدول اليوم"],
  "dash.noAppts": ["No appointments today.", "لا مواعيد اليوم."],
  "dash.activity": ["Activity", "النشاط"],
  "dash.recall": ["Patients due for a check-up", "مرضى حان موعد فحصهم"],
  "dash.recallHint": ["Haven't visited within their recall period.", "لم يزوروا العيادة خلال فترة المتابعة."],
  "dash.recallNone": ["Everyone is up to date.", "الجميع محدّث."],
  "dash.sendReminder": ["Send reminder", "إرسال تذكير"],
  "dash.publicLive": ["Public live page", "صفحة الوضع المباشر العامة"],
  "dash.publicLiveHint": ["Patients check the crowd before they leave home", "المرضى يعرفون الازدحام قبل الخروج من البيت"],

  // queue
  "q.title": ["Live queue", "الدور المباشر"],
  "q.sub": ["Call patients, track chairs and keep waiting times honest.", "ناد المرضى وتابع الكراسي وحافظ على دقة أوقات الانتظار."],
  "q.inChair": ["In the chair", "على الكرسي"],
  "q.finish": ["Visit finished", "انتهت الزيارة"],
  "q.overrun": ["Running over", "تجاوز الوقت"],
  "q.waiting": ["Waiting", "في الانتظار"],
  "q.noWaiting": ["No one waiting.", "لا أحد في الانتظار."],
  "q.arrived": ["arrived", "وصل"],
  "q.emergency": ["Emergency", "طارئ"],
  "q.emergencyHint": ["Emergency: jumps to the front of the queue", "حالة طارئة: تتقدم لأول الدور"],
  "q.onTheWay": ["On the way", "في الطريق"],
  "q.walkin": ["Walk-in", "بدون موعد"],
  "q.markArrived": ["Arrived", "وصل"],
  "q.makeUrgent": ["Make urgent", "اجعله طارئاً"],
  "q.normal": ["Normal", "عادي"],
  "q.remove": ["Remove", "إزالة"],
  "q.call": ["Call patient", "نادِ المريض"],
  "q.runningLate": ["Running late", "تأخير"],
  "q.onTime": ["On time", "في الوقت"],
  "q.expected": ["Expected today", "المتوقعون اليوم"],
  "q.doneToday": ["{n} patients seen today", "{n} مريض تمت معاينتهم اليوم"],
  "q.noExpected": ["Everyone has checked in.", "الجميع سجّل وصوله."],
  "q.checkIn": ["Patient arrived", "المريض وصل"],
  "q.addToQueue": ["Add to queue", "إضافة للدور"],
  "q.procedures": ["Procedures performed", "الإجراءات المنفذة"],
  "q.notePlaceholder": ["Visit notes (optional)", "ملاحظات الزيارة (اختياري)"],
  "q.invoiceTotal": ["Invoice total", "إجمالي الفاتورة"],
  "q.completeVisit": ["Complete visit & create invoice", "إنهاء الزيارة وإنشاء الفاتورة"],

  // appointments
  "ap.title": ["Appointments", "المواعيد"],
  "ap.sub": ["Daily schedule per doctor with a smart waiting list.", "جدول يومي لكل طبيب مع قائمة انتظار ذكية."],
  "ap.new": ["New appointment", "موعد جديد"],
  "ap.today": ["Go to today", "اذهب لليوم"],
  "ap.closed": ["The clinic is closed on this day (Friday).", "العيادة مغلقة في هذا اليوم (الجمعة)."],
  "ap.appts": ["appointments", "موعد"],
  "ap.none": ["No appointments.", "لا مواعيد."],
  "ap.cancel": ["Cancel", "إلغاء"],
  "ap.waitlist": ["Waiting list", "قائمة الانتظار"],
  "ap.waitlistHint": ["When an appointment is cancelled, the first matching patient is notified automatically.", "عند إلغاء أي موعد، يُبلَّغ أول مريض مناسب تلقائياً."],
  "ap.noSlots": ["No free slots on this day.", "لا مواعيد متاحة في هذا اليوم."],
  "ap.confirm": ["Confirm booking", "تأكيد الحجز"],

  // patients
  "p.new": ["New patient", "مريض جديد"],
  "p.search": ["Search name or phone...", "ابحث بالاسم أو الهاتف..."],
  "p.select": ["Select a patient to see the file", "اختر مريضاً لعرض ملفه"],
  "p.years": ["yrs", "سنة"],
  "p.lastVisit": ["Last visit", "آخر زيارة"],
  "p.balance": ["Balance", "المتبقي"],
  "p.alerts": ["Medical alerts", "تنبيهات طبية"],
  "p.allergies": ["Allergies", "الحساسية"],
  "p.conditions": ["Conditions", "الحالات الطبية"],
  "p.overview": ["Overview", "نظرة عامة"],
  "p.chart": ["Dental chart", "مخطط الأسنان"],
  "p.plan": ["Treatment & billing", "العلاج والفواتير"],
  "p.rx": ["Prescriptions", "الوصفات"],
  "p.notes": ["Notes", "الملاحظات"],
  "p.details": ["Details", "التفاصيل"],
  "p.notesField": ["Notes", "ملاحظات"],
  "p.recall": ["Check-up reminder every", "تذكير بالفحص كل"],
  "p.visits": ["Visit history", "سجل الزيارات"],
  "p.save": ["Save patient", "حفظ المريض"],
  "p.tooth": ["Tooth", "السن"],
  "p.plannedDot": ["Planned treatment", "علاج مخطط"],
  "p.tapTooth": ["Tap a tooth to set its condition or plan a treatment.", "اضغط على سن لتحديد حالته أو تخطيط علاج له."],
  "p.addToPlan": ["Add to plan", "أضف للخطة"],
  "p.treatmentPlan": ["Treatment plan", "خطة العلاج"],
  "p.estimate": ["Estimate", "التقدير"],
  "p.noPlan": ["No planned treatments.", "لا علاجات مخططة."],
  "p.completed": ["Completed treatments", "العلاجات المنجزة"],
  "p.markDone": ["Mark done", "تم التنفيذ"],

  // rx / notes
  "rx.new": ["New prescription", "وصفة جديدة"],
  "rx.drug": ["Medicine", "الدواء"],
  "rx.dose": ["Dose / instructions", "الجرعة / التعليمات"],
  "rx.days": ["Days", "الأيام"],
  "rx.add": ["Add", "إضافة"],
  "rx.save": ["Save prescription", "حفظ الوصفة"],
  "n.placeholder": ["Write a clinical note...", "اكتب ملاحظة سريرية..."],
  "n.save": ["Save note", "حفظ الملاحظة"],

  // billing
  "b.title": ["Billing", "الفواتير"],
  "b.sub": ["Invoices are created automatically when a visit is completed.", "تُنشأ الفواتير تلقائياً عند إنهاء الزيارة."],
  "b.unpaidOnly": ["Unpaid only", "غير المسددة فقط"],
  "b.billed": ["Billed", "المفوتر"],
  "b.collected": ["Collected", "المحصّل"],
  "b.paid": ["Paid", "مدفوع"],
  "b.allClear": ["Nothing to show.", "لا شيء لعرضه."],
  "b.receive": ["Receive payment", "استلام دفعة"],
  "b.payAll": ["Settle balance", "تسديد الرصيد"],
  "b.receipt": ["Receipt", "إيصال"],
  "b.receiptSub": ["Payment receipt", "إيصال دفع"],
  "b.print": ["Print", "طباعة"],
  "b.patient": ["Patient", "المريض"],
  "b.total": ["Total", "الإجمالي"],

  // reports
  "r.title": ["Reports", "التقارير"],
  "r.sub": ["Understand how the clinic is performing.", "افهم أداء العيادة."],
  "r.revenue7": ["Revenue (7 days)", "الإيراد (7 أيام)"],
  "r.avgWait": ["Average wait", "متوسط الانتظار"],
  "r.avgWaitHint": ["from arrival to chair", "من الوصول حتى الكرسي"],
  "r.noShow": ["No-show rate", "نسبة عدم الحضور"],
  "r.rating": ["Patient rating", "تقييم المرضى"],
  "r.reviews": ["reviews", "تقييم"],
  "r.revenueChart": ["Revenue per day", "الإيراد اليومي"],
  "r.visitsChart": ["Visits per day", "الزيارات اليومية"],
  "r.statusMix": ["Appointment outcomes", "حالات المواعيد"],
  "r.topProcedures": ["Top procedures by revenue", "أعلى الإجراءات إيراداً"],
  "r.feedback": ["Patient feedback", "آراء المرضى"],

  // settings
  "set.title": ["Settings", "الإعدادات"],
  "set.sub": ["Doctors, services, prices and shortcuts.", "الأطباء والخدمات والأسعار والاختصارات."],
  "set.doctors": ["Doctors", "الأطباء"],
  "set.hours": ["Working hours: Sat-Thu 09:00-17:00, lunch break 13:00-14:00, closed on Fridays.", "ساعات العمل: السبت-الخميس 09:00-17:00، استراحة 13:00-14:00، مغلق يوم الجمعة."],
  "set.links": ["Shareable screens", "شاشات قابلة للمشاركة"],
  "set.linksHint": ["Put the live page link on Google Maps, WhatsApp or a QR code at the door.", "ضع رابط الصفحة المباشرة على خرائط جوجل أو واتساب أو QR عند الباب."],
  "set.liveLink": ["Public live status page", "صفحة الوضع المباشر العامة"],
  "set.tvLink": ["Waiting-room TV screen", "شاشة التلفاز في الانتظار"],
  "set.services": ["Services & prices", "الخدمات والأسعار"],
  "set.duration": ["Minutes", "الدقائق"],
  "set.price": ["Price ($)", "السعر ($)"],
  "set.add": ["Add service", "إضافة خدمة"],

  // live (public)
  "live.title": ["Clinic status, live", "وضع العيادة مباشرة"],
  "live.sub": ["Check how busy we are before you leave home.", "اعرف مدى الازدحام قبل أن تخرج من البيت."],
  "live.now": ["Live right now", "مباشر الآن"],
  "live.level.quiet": ["Quiet: come anytime", "هادئ: تعال في أي وقت"],
  "live.level.busy": ["Moderately busy", "مزدحم قليلاً"],
  "live.level.crowded": ["Very busy", "مزدحم جداً"],
  "live.advice.quiet": ["Almost no waiting. A great time to visit.", "تقريباً بدون انتظار. وقت ممتاز للزيارة."],
  "live.advice.busy": ["There is a short wait. Reserve your place and leave home later.", "هناك انتظار قصير. احجز مكانك واخرج من البيت لاحقاً."],
  "live.advice.crowded": ["Long wait expected. Reserve your place and we will tell you when to leave.", "انتظار طويل متوقع. احجز مكانك وسنخبرك متى تخرج."],
  "live.inClinic": ["People in clinic", "داخل العيادة"],
  "live.waiting": ["Waiting", "ينتظرون"],
  "live.waitNew": ["Wait if you arrive now", "الانتظار لو وصلت الآن"],
  "live.chairBusy": ["Chair in use", "الكرسي مشغول"],
  "live.chairFree": ["Chair free", "الكرسي فارغ"],
  "live.late": ["Running {n} min late", "متأخر {n} دقيقة"],
  "live.viewAs": ["Track the queue as", "تتبّع الدور كـ"],
  "live.autoRefresh": ["Updates automatically. Open this page on a phone while the clinic uses the Queue screen to see it change live.", "يتحدّث تلقائياً. افتح هذه الصفحة على الجوال بينما تستخدم العيادة شاشة الدور لترى التغيير مباشرة."],

  // tracker
  "track.title": ["Track my turn", "تتبّع دوري"],
  "track.yourTicket": ["Your ticket", "تذكرتك"],
  "track.inChair": ["You are with the doctor now", "أنت عند الطبيب الآن"],
  "track.ahead": ["people ahead of you", "أشخاص قبلك"],
  "track.minWait": ["minutes wait", "دقيقة انتظار"],
  "track.expected": ["expected at", "الدخول المتوقع"],
  "track.you": ["You", "أنت"],
  "track.leaveNow": ["Leave now to arrive on time!", "اخرج الآن لتصل في الوقت!"],
  "track.leaveIn": ["Leave in {n} min (at {time})", "اخرج بعد {n} دقيقة (الساعة {time})"],
  "track.leaveHint": ["Based on live queue and your travel time.", "بناءً على الدور المباشر ووقت وصولك."],
  "track.travel": ["Travel time", "وقت الوصول"],
  "track.imHere": ["I've arrived", "وصلت"],
  "track.cancelSpot": ["Release my spot", "إلغاء مكاني"],
  "track.notify": ["We message you when you are next, or if the doctor runs late.", "سنراسلك عندما يصبح دورك التالي أو إذا تأخر الطبيب."],
  "track.joinTitle": ["Wait at home, not at the clinic", "انتظر في البيت وليس في العيادة"],
  "track.joinText": ["Press one button to save your place in line. We will tell you when it is time to leave home.", "اضغط زراً واحداً ليُحفظ مكانك في الدور. سنخبرك متى يحين وقت الخروج من البيت."],
  "track.ifYouJoin": ["If you join now", "لو انضممت الآن"],
  "track.peopleAhead": ["people ahead", "أشخاص قبلك"],
  "track.join": ["Reserve my place", "احجز مكاني في الدور"],

  // patient home
  "ph.hello": ["Hello, {name}", "أهلاً، {name}"],
  "ph.sub": ["Your clinic, in your pocket.", "عيادتك في جيبك."],
  "ph.upcoming": ["Upcoming appointments", "مواعيدك القادمة"],
  "ph.noUpcoming": ["No upcoming appointments. Book one in a minute.", "لا مواعيد قادمة. احجز موعداً خلال دقيقة."],
  "ph.address": ["DentaCare Clinic, Amman", "عيادة دينتاكير، عمّان"],
  "ph.balanceDue": ["You have an unpaid balance", "لديك رصيد غير مسدد"],
  "ph.waitlist": ["You're on the waiting list", "أنت في قائمة الانتظار"],
  "ph.waiting": ["Waiting", "بالانتظار"],
  "ph.latest": ["Latest message", "آخر رسالة"],
  "ph.call": ["Call the clinic", "اتصل بالعيادة"],

  // booking wizard
  "bk.sub": ["Pick a service, a doctor and a time. No phone call needed.", "اختر الخدمة والطبيب والوقت. بدون اتصال هاتفي."],
  "bk.step1": ["1. What do you need?", "1. ماذا تحتاج؟"],
  "bk.step2": ["2. Choose a doctor", "2. اختر الطبيب"],
  "bk.step3": ["3. Pick a day and time", "3. اختر اليوم والوقت"],
  "bk.back": ["Back", "رجوع"],
  "bk.closed": ["Closed", "مغلق"],
  "bk.noSlots": ["No free slots on this day. Try another day or join the waiting list.", "لا مواعيد متاحة في هذا اليوم. جرّب يوماً آخر أو انضم لقائمة الانتظار."],
  "bk.joinWaitlist": ["Notify me if a slot opens", "أخبرني إذا توفر موعد"],
  "bk.onWaitlist": ["You're on the waiting list", "أنت في قائمة الانتظار"],
  "bk.doneTitle": ["You're booked!", "تم الحجز!"],
  "bk.doneHint": ["A confirmation was sent to your messages. We'll remind you before the visit.", "أُرسل تأكيد إلى رسائلك. سنذكّرك قبل الزيارة."],
  "bk.another": ["Book another", "حجز آخر"],

  // records
  "rec.payOnline": ["Pay online (demo)", "ادفع إلكترونياً (تجريبي)"],
  "rec.rateTitle": ["How was your visit today?", "كيف كانت زيارتك اليوم؟"],
  "rec.comment": ["Tell us more (optional)", "أخبرنا المزيد (اختياري)"],
  "rec.submit": ["Send feedback", "إرسال التقييم"],
  "rec.doctorNotes": ["Doctor's notes", "ملاحظات الطبيب"],
  "inbox.sub": ["Reminders, queue updates and offers.", "تذكيرات وتحديثات الدور وعروض."],
  "inbox.markAll": ["Mark all as read", "تحديد الكل كمقروء"],

  // tv
  "tv.welcome": ["Welcome. Please wait for your number.", "أهلاً بك. يرجى انتظار رقمك."],
  "tv.serving": ["Now serving", "يُخدَم الآن"],
  "tv.next": ["Next up", "التالي"],

  // plain-language guide and big buttons
  "how.show": ["How does this work?", "كيف يعمل هذا؟"],
  "how.hide": ["Got it, hide this", "فهمت، أخفِ هذا"],
  "how.staff.title": ["Three simple steps for every patient", "ثلاث خطوات بسيطة لكل مريض"],
  "how.staff.1": ["When a patient arrives, press “Patient arrived”.", "عندما يصل المريض، اضغط «المريض وصل»."],
  "how.staff.2": ["When the doctor is free, press “Call next patient”.", "عندما يصبح الطبيب متفرغاً، اضغط «نادِ المريض التالي»."],
  "how.staff.3": ["When finished, press “Visit finished” and choose what was done. The bill is made for you.", "عند الانتهاء، اضغط «انتهت الزيارة» واختر ما تم. الفاتورة تُنشأ تلقائياً."],
  "how.patient.title": ["Simple steps for your visit", "خطوات بسيطة لزيارتك"],
  "how.patient.1": ["Press “Book an appointment” and choose a time.", "اضغط «احجز موعداً» واختر الوقت."],
  "how.patient.2": ["On the day, press “Reserve my place” and wait at home.", "في يوم الموعد، اضغط «احجز مكاني في الدور» وانتظر في البيت."],
  "how.patient.3": ["We tell you when to leave. Come, and the doctor will see you.", "نخبرك متى تخرج. تعال وسيستقبلك الطبيب."],
  "dash.a1": ["Patient arrived", "المريض وصل"],
  "dash.a1s": ["Put them in the line", "ضعه في الدور"],
  "dash.a2": ["Call next patient", "نادِ المريض التالي"],
  "dash.a2s": ["When the doctor is free", "عندما يكون الطبيب متفرغاً"],
  "dash.a3": ["Book appointment", "احجز موعداً"],
  "dash.a3s": ["Choose day and time", "اختر اليوم والوقت"],
  "dash.a4": ["New patient", "مريض جديد"],
  "dash.a4s": ["Open a patient file", "افتح ملف مريض"],
  "dash.more": ["More details (charts, messages, reminders)", "المزيد من التفاصيل (رسوم، رسائل، تذكيرات)"],
  "q.callNext": ["Call next patient", "نادِ المريض التالي"],
  "ph.act.book": ["Book an appointment", "احجز موعداً"],
  "ph.act.bookSub": ["Choose a day and time", "اختر اليوم والوقت"],
  "ph.act.live": ["Is the clinic busy now?", "هل العيادة مزدحمة الآن؟"],
  "ph.act.liveSub": ["See how long you would wait", "اعرف كم ستنتظر"],
  "ph.act.records": ["My file", "ملفي"],
  "ph.act.recordsSub": ["Treatments, bills, prescriptions", "العلاجات والفواتير والوصفات"],

  // toasts
  "toast.arrived": ["Welcome! The clinic knows you've arrived.", "أهلاً بك! عرفت العيادة بوصولك."],
  "toast.booked": ["Appointment booked", "تم حجز الموعد"],
  "toast.called": ["{name} was called in", "تم نداء {name}"],
  "toast.cancelled": ["Appointment cancelled", "تم إلغاء الموعد"],
  "toast.checkedIn": ["Checked in and added to the queue", "تم تسجيل الوصول والإضافة للدور"],
  "toast.delay": ["Waiting patients were told you're {n} min late", "تم إبلاغ المنتظرين بتأخرك {n} دقيقة"],
  "toast.delayCleared": ["Back on schedule", "عدنا للجدول"],
  "toast.joined": ["Your place is saved", "تم حفظ مكانك"],
  "toast.noteSaved": ["Note saved", "تم حفظ الملاحظة"],
  "toast.paid": ["Payment recorded", "تم تسجيل الدفعة"],
  "toast.patientAdded": ["Patient added", "تمت إضافة المريض"],
  "toast.planAdded": ["Added to the treatment plan", "أُضيف لخطة العلاج"],
  "toast.recallSent": ["Reminder sent to {name}", "تم إرسال تذكير إلى {name}"],
  "toast.rxSaved": ["Prescription saved", "تم حفظ الوصفة"],
  "toast.serviceAdded": ["Service added", "تمت إضافة الخدمة"],
  "toast.spotReleased": ["Your spot was released", "تم إلغاء مكانك"],
  "toast.thanks": ["Thank you for your feedback!", "شكراً على تقييمك!"],
  "toast.visitDone": ["Visit completed and invoice created", "اكتملت الزيارة وأُنشئت الفاتورة"],
  "toast.waitlisted": ["We'll notify you if a slot opens", "سنبلغك إذا توفر موعد"],
};
